name: FuelRescue Backend CI/CD service

on:
  push:
    branches: ['deploy']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV }}" > .env
          # Fix MongoDB connection string protocol if needed
          sed -i 's/mongo:\/\//mongodb:\/\//g' .env
          echo "Verifying env file content (masked):"
          grep -v "SECRET\\|PASSWORD\\|TOKEN" .env | sed 's/=.*/=***/'
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: tesals/tekcify_backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: |
            ENV_FILE=.env

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: deploy-application
      uses: nekiro/ssh-job@main
      with:
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        user: ${{ secrets.SSH_USER }}
        command: >
          mkdir -p /home/${{ secrets.SSH_USER }}/tekcify &&
          cd /home/${{ secrets.SSH_USER }}/tekcify &&
          echo '${{ secrets.ENV }}' > .env &&
          ls -la .env &&
          cat .env | grep -v "SECRET\|PASSWORD\|TOKEN" | sed 's/=.*/=***/' &&
          docker ps -a --filter "name=^tekcifyAuth" --format "{{.ID}}" | xargs -r docker rm -f && 
          docker pull tesals/tekcify_backend:latest &&
          docker run -p "8009:4000" -e DATABASE_URL="${{ secrets.DATABASE_URL }}"  --env-file ~/tekcify-auth/.env --name tekcifyAuth-$(date +%Y-%m-%d-%H-%M-%S) -d tesals/tekcify_backend:latest

